Require sufficiently new cryptography dependency
Using cryptography<3.5 (or 35, apparently) leads to this error message:

    TypeError: generate_parameters() missing 1 required positional
    argument: 'backend'

See issue #61.